import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.scss";
import { Navigation } from "./components/navigation";
const geistSans = localFont({
  src: "./styles/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./styles/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Next App Example",
  description: "Generated by create next app",
};

const navigation = [
  { name: 'Home', href: '/' },
  { name: 'Product', href: '/product?q=dummytext' },
  { name: '[id]', href: '/product/dummytext' }
]

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
